### ISSUE TITLE
Can't draw circles and rectangles.

### ISSUE THREAD

**Issue by seanmorris** [VBproDev/Canvascript#2]
I'd also like to be able to select an outline/fill color, or no color at all for transparent.

**Comment by VGBijpuria** [comment]
Like you want to color shapes? Since Canavscript draws only lines, it gives you greater flexibility to draw whatever shape you want and then color it whatever you want. You can color by increasing the width of your brush and then filling the entire shape with your color. If you have any idea on how curves can be made, then please reply or I will close this issue

**Comment by seanmorris** [comment]
Check out these examples:

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/rect

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/ellipse

**Comment by VGBijpuria** [comment]
Any ideas on how to implement curves in Canvascript, I am ready to do major refactoring of the codebase as this seems to be a worthwhile feature to have.
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/bezierCurveTo

**Comment by VGBijpuria** [comment]
Let's a raise a separate issue for curves and close this one if you are interested.

**Comment by VGBijpuria** [comment]
Closing this issue now due to inactivity.
