### ISSUE TITLE
UI gets broken when new line gets drawn

### ISSUE THREAD

**Issue by VGBijpuria** [VBproDev/Canvascript#24]
When you draw more than 1 line on the canvas, the section where you can set line curvature gets broken, instead it should stay as it originally was. Fix this.

**Comment by DIlkhush00** [comment]
Hi @VBproDev , I would like to fix it

**Comment by DIlkhush00** [comment]
Hi @VBproDev , I noticed that the below code seems to be causing that unwanted behaviour :

https://github.com/VBproDev/Canvascript/blob/25fc882718e185ff2b994f70287bd56e1c4a9446/script.ts#L289-L292

If this code is necessary, the value of `curveInputContainer.innerHTML` may need to be adjusted to align with the existing styles. Otherwise, it's better to simply **remove** it.

**Comment by VGBijpuria** [comment]
@DIlkhush00 The code is unnecessary with the new UI, so I think we can remove this. Do you wish to raise a PR in this regard?

**Comment by DIlkhush00** [comment]
Yeah, sure

**Comment by VGBijpuria** [comment]
@DIlkhush00 do you want to be a collaborator of this project?

**Comment by DIlkhush00** [comment]
@VBproDev Thank you for the offer! I’ll pass for now but happy to help when I can 🙃
